"""
Paper 표 (정규화 변종만) 엑셀 생성.
사용자 IN/OUT 정의 표 + sp NLL (full+tail) 결과 매핑.
"""
import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
from openpyxl.utils import get_column_letter

OUT_PATH = r"D:\projects\homeostatic-market\result_for_paper_normalized_table.xlsx"

ROWS = [
    # 1
    {"#": 1, "model": "Base (K2_pure_ppbond)",
     "IN cond": "tbill_wr, excess_liq_wr (2ch × 104w)",
     "IN past target": "sp_return (1ch × past 52w)",
     "OUT future target": "sp_return (1ch × future 52w)",
     "sp NLL full median": -1.9971, "full mean ± std": "-1.8624 ± 0.263",
     "tail NLL median": -0.2019,    "tail mean ± std": "+0.1147 ± 0.947",
     "n": 5, "매핑 결과 #": 1,
     "비고": "정규 대상 없음"},
    # 2
    {"#": 2, "model": "Base (without liquidity)",
     "IN cond": "tbill_wr (1ch × 104w)",
     "IN past target": "sp_return (1ch × past 52w)",
     "OUT future target": "sp_return (1ch × future 52w)",
     "sp NLL full median": -1.6700, "full mean ± std": "-1.4065 ± 0.562",
     "tail NLL median": +1.3730,    "tail mean ± std": "+2.3055 ± 2.500",
     "n": 5, "매핑 결과 #": 2,
     "비고": "정규 대상 없음"},
    # 3
    {"#": 3, "model": "Base (add bondpp)",
     "IN cond": "tbill_wr, excess_liq_wr, bondpp_3m (3ch × 104w)",
     "IN past target": "sp_return (1ch × past 52w)",
     "OUT future target": "sp_return (1ch × future 52w)",
     "sp NLL full median": -1.7307, "full mean ± std": "-1.3892 ± 0.763",
     "tail NLL median": -0.6876,    "tail mean ± std": "-0.2278 ± 1.932",
     "n": 5, "매핑 결과 #": 3,
     "비고": "⚠ raw bondpp 결과만 있음. 정규 bondpp 학습 미실시 — 새 학습 필요"},
    # 4
    {"#": 4, "model": "Stage 1 (MacroExpander)",
     "IN cond": "past: tbill_wr, excess_liq_wr (2ch × 52w) / future: tbill_wr (1ch × 52w)",
     "IN past target": "excess_liq_wr (1ch × past 52w)",
     "OUT future target": "excess_liq_wr (1ch × future 52w)",
     "sp NLL full median": "n/a", "full mean ± std": "n/a",
     "tail NLL median": "n/a",    "tail mean ± std": "n/a",
     "n": 0, "매핑 결과 #": 4,
     "비고": "sp_return target 없음 → sp NLL 평가 불가"},
    # 5
    {"#": 5, "model": "Stage 1 (vix)",
     "IN cond": "past: tbill_wr, excess_liq_wr (2ch × 52w) / future: tbill_wr (1ch × 52w)",
     "IN past target": "vix_wr (1ch × past 52w)",
     "OUT future target": "vix_wr (1ch × future 52w)",
     "sp NLL full median": "n/a", "full mean ± std": "n/a",
     "tail NLL median": "n/a",    "tail mean ± std": "n/a",
     "n": 0, "매핑 결과 #": 24,
     "비고": "sp_return target 없음 → sp NLL 평가 불가. 정규 vix 로 학습됨 (ckpt 별도 존재)"},
    # 6
    {"#": 6, "model": "Stage 2 (PriceGenerator)",
     "IN cond": "past: tbill_wr, excess_liq_w (2ch × 52w) / future: tbill_wr, excess_liq_w (generated by stage1) (3ch × 52w)",
     "IN past target": "sp_return (1ch × past 52w)",
     "OUT future target": "sp_return (1ch × future 52w)",
     "sp NLL full median": -1.8694, "full mean ± std": "-1.4332 ± 0.741",
     "tail NLL median": -0.2814,    "tail mean ± std": "-0.2985 ± 0.865",
     "n": 5, "매핑 결과 #": 6,
     "비고": "정규 대상 없음"},
    # 7
    {"#": 7, "model": "Stage 2 (대조군)",
     "IN cond": "past: tbill_wr, excess_liq_w (3ch) / future: tbill_wr (2ch × 52w)",
     "IN past target": "sp_return (1ch × past 52w)",
     "OUT future target": "sp_return (1ch × future 52w)",
     "sp NLL full median": -1.9264, "full mean ± std": "-1.7438 ± 0.381",
     "tail NLL median": +0.3768,    "tail mean ± std": "+0.6128 ± 1.088",
     "n": 5, "매핑 결과 #": 7,
     "비고": "정규 대상 없음"},
    # 8
    {"#": 8, "model": "MTL(2 채널, liq)",
     "IN cond": "past: tbill_wr (2ch × 52w) / future: tbill_wr (1ch × 52w)",
     "IN past target": "excess_liq_wr (1ch × past), sp_return (1ch × past 52w)",
     "OUT future target": "excess_liq_wr (1ch × future), sp_return (1ch × future 52w)",
     "sp NLL full median": -2.0880, "full mean ± std": "-1.9651 ± 0.195",
     "tail NLL median": -0.9914,    "tail mean ± std": "-0.6106 ± 0.835",
     "n": 5, "매핑 결과 #": 8,
     "비고": "정규 대상 없음"},
    # 9
    {"#": 9, "model": "MTL(2 채널, vix)",
     "IN cond": "past: tbill_wr, excess_liq_wr (2ch × 52w) / future: tbill_wr (1ch × 52w)",
     "IN past target": "vix_wr (1ch × past), sp_return (1ch × past 52w)",
     "OUT future target": "vix_wr (1ch × future), sp_return (1ch × future 52w)",
     "sp NLL full median": -1.8463, "full mean ± std": "-1.9170 ± 0.158",
     "tail NLL median": -1.0787,    "tail mean ± std": "-0.9200 ± 0.357",
     "n": 5, "매핑 결과 #": 25,
     "비고": "vix 정규"},
    # 10
    {"#": 10, "model": "MTL(2 채널, bondpp_3m)",
     "IN cond": "past: tbill_wr, excess_liq_w (2ch × 52w) / future: tbill_wr (1ch × 52w)",
     "IN past target": "sp_return (1ch × past 52w), bondpp_3m (1ch × past 52w)",
     "OUT future target": "sp_return (1ch × future 52w), bondpp_3m (1ch × future 52w)",
     "sp NLL full median": -1.9758, "full mean ± std": "-1.9445 ± 0.206",
     "tail NLL median": -1.0932,    "tail mean ± std": "-1.2595 ± 0.325",
     "n": 5, "매핑 결과 #": 12,
     "비고": "bondpp 정규"},
    # 11
    {"#": 11, "model": "MTL(2 채널, stockpp_3m)",
     "IN cond": "past: tbill_wr, excess_liq_wr (2ch × 52w) / future: tbill_wr (1ch × 52w)",
     "IN past target": "stockpp_3m (1ch × past), sp_return (1ch × past 52w)",
     "OUT future target": "stockpp_3m (1ch × future), sp_return (1ch × future 52w)",
     "sp NLL full median": -2.0488, "full mean ± std": "-1.8872 ± 0.504",
     "tail NLL median": -0.9957,    "tail mean ± std": "-0.9685 ± 0.542",
     "n": 5, "매핑 결과 #": 22,
     "비고": "stockpp 정규"},
    # 12
    {"#": 12, "model": "MTL(3 채널, bondpp_3m, vix)",
     "IN cond": "past: tbill_wr, excess_liq_w (2ch × 52w) / future: tbill_wr (1ch × 52w)",
     "IN past target": "sp_return, bondpp_3m, vix_wr (1ch × past 52w each)",
     "OUT future target": "sp_return, bondpp_3m, vix_wr (1ch × future 52w each)",
     "sp NLL full median": -1.6557, "full mean ± std": "-1.6469 ± 0.436",
     "tail NLL median": -0.5905,    "tail mean ± std": "-0.2352 ± 1.425",
     "n": 5, "매핑 결과 #": 26,
     "비고": "⚠ bondpp+vix 동시 정규 — 학습 깨짐 (분산 폭증)"},
    # 13
    {"#": 13, "model": "MTL(3 채널, bondpp_3m, stockpp_3m)",
     "IN cond": "past: tbill_wr, excess_liq_w (2ch × 52w) / future: tbill_wr (1ch × 52w)",
     "IN past target": "sp_return, bondpp_3m, stockpp_3m (1ch × past 52w each)",
     "OUT future target": "sp_return, bondpp_3m, stockpp_3m (1ch × future 52w each)",
     "sp NLL full median": -2.1377, "full mean ± std": "-2.1368 ± 0.108",
     "tail NLL median": -1.5461,    "tail mean ± std": "-1.4756 ± 0.312",
     "n": 5, "매핑 결과 #": 23,
     "비고": "bondpp+stockpp 정규 (이미지 표 target 컬럼의 vix_wr 표기는 stockpp_3m 의 typo 로 추정)"},
    # 14 [bold] — 가설 A: cond 2ch (with liq), 표기상 excess_liq_wr 누락
    {"#": 14, "model": "MTL(3 채널, liq, bondpp_3m) [bold]",
     "IN cond": "past: tbill_wr (1ch × 52w) / future: tbill_wr (1ch × 52w)  ※ cond 2ch 가능성 (표기 검증 필요)",
     "IN past target": "excess_liq_wr, sp_return, bondpp_3m (1ch × past 52w each)",
     "OUT future target": "excess_liq_wr, sp_return, bondpp_3m (1ch × future 52w each)",
     "sp NLL full median": -2.1907, "full mean ± std": "-2.1870 ± 0.084",
     "tail NLL median": -1.7336,    "tail mean ± std": "-1.6142 ± 0.297",
     "n": 5, "매핑 결과 #": 14,
     "비고": "★ best (mtl_bp3_normbp). bondpp 정규. 가설: cond 가 실제 2ch (tbill+excess_liq) — 코드 default 일치"},
    # 15 [bold]
    {"#": 15, "model": "MTL(3 채널, liq, vix) [bold]",
     "IN cond": "past: tbill_wr (1ch × 52w) / future: tbill_wr (1ch × 52w)  ※ cond 2ch 가능성 (표기 검증 필요)",
     "IN past target": "excess_liq_wr, sp_return, vix_wr (1ch × past 52w each)",
     "OUT future target": "excess_liq_wr, sp_return, vix_wr (1ch × future 52w each)",
     "sp NLL full median": -2.1213, "full mean ± std": "-1.9164 ± 0.384",
     "tail NLL median": -1.3013,    "tail mean ± std": "-0.8250 ± 0.752",
     "n": 5, "매핑 결과 #": 27,
     "비고": "vix 정규 (mtl3_normvix). 분산 큰 편 (std 0.38)"},
    # 16 — 가설: cond 1ch (no-liq), 행 14 와 표기 동일하나 cond 다른 변종
    {"#": 16, "model": "MTL(3 채널, liq, bondpp_3m)",
     "IN cond": "past: tbill_wr (1ch × 52w) / future: tbill_wr (1ch × 52w)  ※ no-liq cond 1ch 가정",
     "IN past target": "excess_liq_wr, sp_return, bondpp_3m (1ch × past 52w each)",
     "OUT future target": "excess_liq_wr, sp_return, bondpp_3m (1ch × future 52w each)",
     "sp NLL full median": -1.8947, "full mean ± std": "-1.9977 ± 0.175",
     "tail NLL median": -1.1694,    "tail mean ± std": "-1.1074 ± 0.439",
     "n": 5, "매핑 결과 #": 18,
     "비고": "행 14 와 표기 동일 — 가설: 14=cond 2ch (with liq), 16=cond 1ch (no-liq) ablation. 사용자 확인 필요"},
    # 17 [bold]
    {"#": 17, "model": "MTL(3 채널, bondpp_3m, vix) [bold]",
     "IN cond": "past: tbill_wr (1ch × 52w) / future: tbill_wr (1ch × 52w)  ※ no-liq cond 1ch",
     "IN past target": "vix_wr, sp_return, bondpp_3m (1ch × past 52w each)",
     "OUT future target": "vix_wr, sp_return, bondpp_3m (1ch × future 52w each)",
     "sp NLL full median": -1.8183, "full mean ± std": "-1.6285 ± 0.389",
     "tail NLL median": -0.5148,    "tail mean ± std": "-0.4356 ± 0.644",
     "n": 5, "매핑 결과 #": 28,
     "비고": "⚠ bondpp+vix 동시 정규 + no-liq cond — 학습 깨짐 (분산 0.39)"},
]

COLUMNS = [
    "#", "model", "IN cond", "IN past target", "OUT future target",
    "sp NLL full median", "full mean ± std",
    "tail NLL median", "tail mean ± std",
    "n", "매핑 결과 #", "비고",
]

df = pd.DataFrame(ROWS, columns=COLUMNS)

with pd.ExcelWriter(OUT_PATH, engine="openpyxl") as w:
    df.to_excel(w, index=False, sheet_name="Paper_Table_Normalized")

# 폰트, 컬럼 너비, 강조 행 fill
wb = load_workbook(OUT_PATH)
ws = wb["Paper_Table_Normalized"]

header_font = Font(bold=True, color="FFFFFF")
header_fill = PatternFill("solid", fgColor="305496")
best_fill   = PatternFill("solid", fgColor="FFF2CC")  # row 14 best
warn_fill   = PatternFill("solid", fgColor="FCE4D6")  # rows 12, 17 (악화)
nockpt_fill = PatternFill("solid", fgColor="E7E6E6")  # rows 4, 5
center      = Alignment(horizontal="center", vertical="center", wrap_text=True)
left_wrap   = Alignment(horizontal="left",   vertical="center", wrap_text=True)
thin = Side(style="thin", color="999999")
border = Border(left=thin, right=thin, top=thin, bottom=thin)

# header
for col_idx, col_name in enumerate(COLUMNS, start=1):
    cell = ws.cell(row=1, column=col_idx)
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = center
    cell.border = border

# body
for r_idx in range(2, 2 + len(ROWS)):
    row_num = r_idx - 1  # 1..17
    for c_idx, col_name in enumerate(COLUMNS, start=1):
        cell = ws.cell(row=r_idx, column=c_idx)
        cell.border = border
        if col_name in ("model", "IN cond", "IN past target", "OUT future target", "비고"):
            cell.alignment = left_wrap
        else:
            cell.alignment = center
    # row-level fill
    if row_num == 14:
        for c_idx in range(1, len(COLUMNS) + 1):
            ws.cell(row=r_idx, column=c_idx).fill = best_fill
    elif row_num in (12, 17):
        for c_idx in range(1, len(COLUMNS) + 1):
            ws.cell(row=r_idx, column=c_idx).fill = warn_fill
    elif row_num in (4, 5):
        for c_idx in range(1, len(COLUMNS) + 1):
            ws.cell(row=r_idx, column=c_idx).fill = nockpt_fill

# 컬럼 너비
widths = {
    "#":                   5,
    "model":              32,
    "IN cond":            56,
    "IN past target":     50,
    "OUT future target":  50,
    "sp NLL full median": 14,
    "full mean ± std":    18,
    "tail NLL median":    14,
    "tail mean ± std":    18,
    "n":                   5,
    "매핑 결과 #":         10,
    "비고":               60,
}
for c_idx, col_name in enumerate(COLUMNS, start=1):
    ws.column_dimensions[get_column_letter(c_idx)].width = widths[col_name]

# 행 높이 (wrap text 충분)
ws.row_dimensions[1].height = 30
for r in range(2, 2 + len(ROWS)):
    ws.row_dimensions[r].height = 50

# Freeze header
ws.freeze_panes = "A2"

wb.save(OUT_PATH)
print(f"saved: {OUT_PATH}")
print(f"rows: {len(ROWS)}")
