"""Scan colab/dual_3ch/result/ for mamba_flow_ar_*_summary.json files
generated by hyperparam sweeps and print a comparison table.

Each summary contains the spec (d_model, n_mamba_layers, n_flow_layers,
n_flow_hidden, weight_decay, dropout, lr, seed) plus best_val_nll_per_week
and test_eval.{per_week_nll_z, crps_pooled, emd, cvar_1pct_diff,
coverage_95}.

Usage:
  python colab/dual_3ch/sweep_summary.py --fold F_long_A
  python colab/dual_3ch/sweep_summary.py --fold all   # F_long_A / F_long_B / F_long
  python colab/dual_3ch/sweep_summary.py --fold F_long --sort test_nll
"""
import argparse
import glob
import json
import os
import re
import sys

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

HERE = os.path.dirname(os.path.abspath(__file__))


def parse_summary(path):
    """Read one summary.json and return a flat dict of the columns we care about."""
    with open(path) as f:
        s = json.load(f)
    test = s.get("test_eval") or {}
    fname = os.path.basename(path).replace("_summary.json", "")
    # Recover tag (the bit between mamba_flow_ar_ and the fold suffix).
    # File names: mamba_flow_ar_{tag}_{fold} or mamba_flow_ar_{fold}.
    m = re.match(r"mamba_flow_ar_(.*?)_(F_long(?:_A|_B)?)$", fname)
    if m:
        tag, fold = m.group(1), m.group(2)
    else:
        m2 = re.match(r"mamba_flow_ar_(F_long(?:_A|_B)?)$", fname)
        tag = ""
        fold = m2.group(1) if m2 else "?"
    return dict(
        file=fname,
        tag=tag,
        fold=fold,
        d_model=s.get("d_model"),
        n_mamba_layers=s.get("n_mamba_layers"),
        n_flow_layers=s.get("n_flow_layers"),
        n_flow_hidden=s.get("n_flow_hidden"),
        weight_decay=s.get("weight_decay"),
        dropout=s.get("dropout"),
        n_params=s.get("n_params"),
        best_epoch=s.get("best_epoch"),
        val_nll=s.get("best_val_nll_per_week"),
        test_nll=test.get("per_week_nll_z"),
        crps=test.get("crps_pooled"),
        emd=test.get("emd"),
        cvar1_diff=test.get("cvar_1pct_diff"),
        cov95=test.get("coverage_95"),
        std_ratio=test.get("std_ratio"),
    )


def fmt(v, spec=".4f"):
    if v is None:
        return "   --   "
    try:
        return format(v, spec)
    except (ValueError, TypeError):
        return str(v)


def print_table(rows, sort_key):
    if sort_key:
        rows = sorted(
            rows,
            key=lambda r: (r.get(sort_key) is None,
                           r.get(sort_key) if r.get(sort_key) is not None else 0),
        )
    cols = [
        ("tag",            15),
        ("fold",            9),
        ("d_m",             4),
        ("nML",             3),
        ("nFL",             3),
        ("nFH",             3),
        ("wd",              5),
        ("dr",              4),
        ("ep",              3),
        ("val_nll",         8),
        ("test_nll",        9),
        ("crps",            8),
        ("emd",             8),
        ("|CVaR1Δ|",        9),
        ("cov95",           6),
    ]
    header = "  ".join(name.ljust(w) for name, w in cols)
    print(header)
    print("-" * len(header))
    for r in rows:
        cells = [
            (r["tag"] or "(none)")[:15].ljust(15),
            (r["fold"] or "?")[:9].ljust(9),
            str(r.get("d_model") or "-").rjust(4),
            str(r.get("n_mamba_layers") or "-").rjust(3),
            str(r.get("n_flow_layers") or "-").rjust(3),
            str(r.get("n_flow_hidden") or "-").rjust(3),
            fmt(r.get("weight_decay"), ".3f").rjust(5),
            fmt(r.get("dropout"), ".2f").rjust(4),
            str(r.get("best_epoch") or "-").rjust(3),
            fmt(r.get("val_nll"),     "+.4f").rjust(8),
            fmt(r.get("test_nll"),    "+.4f").rjust(9),
            fmt(r.get("crps"),         ".5f").rjust(8),
            fmt(r.get("emd"),          ".5f").rjust(8),
            (fmt(abs(r["cvar1_diff"]), ".4f") if r.get("cvar1_diff") is not None
             else "   --   ").rjust(9),
            fmt(r.get("cov95"),        ".3f").rjust(6),
        ]
        print("  ".join(cells))


def highlight_best(rows, per_fold=True):
    """Identify and print best (lowest test_nll) entry per fold and overall."""
    by_fold = {}
    for r in rows:
        if r.get("test_nll") is None:
            continue
        by_fold.setdefault(r["fold"], []).append(r)
    print()
    for fold, group in by_fold.items():
        best = min(group, key=lambda r: r["test_nll"])
        print(f"  best test_nll @ {fold:8s}: tag={best['tag']!r:18s}  "
              f"d_m={best['d_model']}, nML={best['n_mamba_layers']}, "
              f"nFL={best['n_flow_layers']}, nFH={best['n_flow_hidden']}, "
              f"wd={best['weight_decay']}, dr={best['dropout']}  "
              f"-> test_nll = {best['test_nll']:+.4f}, "
              f"cov95 = {best.get('cov95'):.3f}, "
              f"|CVaR1Δ| = {abs(best.get('cvar1_diff') or 0):.4f}")


def main():
    ap = argparse.ArgumentParser(
        description="Scan mamba_flow_ar_*_summary.json sweep results and print "
                    "a comparison table."
    )
    ap.add_argument("--fold", default="all",
                    help="F_long_A / F_long_B / F_long / all")
    ap.add_argument("--result-dir", default=os.path.join(HERE, "result"))
    ap.add_argument("--sort", default="test_nll",
                    choices=["test_nll", "val_nll", "crps", "emd",
                             "cvar1_diff", "cov95", "tag"],
                    help="sort key (default test_nll, ascending)")
    args = ap.parse_args()

    if not os.path.isdir(args.result_dir):
        sys.exit(f"[FATAL] result dir not found: {args.result_dir}")

    pattern = os.path.join(args.result_dir, "mamba_flow_ar_*_summary.json")
    files = sorted(glob.glob(pattern))
    if not files:
        sys.exit(f"[FATAL] no mamba_flow_ar_*_summary.json files in "
                 f"{args.result_dir}")

    rows = [parse_summary(p) for p in files]
    rows = [r for r in rows if r["fold"] != "?"]
    if args.fold != "all":
        rows = [r for r in rows if r["fold"] == args.fold]
    if not rows:
        sys.exit(f"[FATAL] no rows match fold = {args.fold!r}")

    print("=" * 78)
    print(f" Sweep summary  -  result_dir = {args.result_dir}")
    print(f"   fold filter           = {args.fold!r}")
    print(f"   sort key              = {args.sort!r}")
    print(f"   files matched         = {len(rows)}")
    print("=" * 78)

    if args.fold == "all":
        for fold in sorted(set(r["fold"] for r in rows)):
            group = [r for r in rows if r["fold"] == fold]
            print(f"\n  fold = {fold}  (n = {len(group)})")
            print_table(group, args.sort)
        print()
        highlight_best(rows)
    else:
        print()
        print_table(rows, args.sort)
        print()
        highlight_best(rows)


if __name__ == "__main__":
    main()
