"""Conditional 1D Neural Spline Flow on globally-standardized ε
with **macro condition vector C_t** as Flow context (paper main thesis).

Paper thesis (regime-conditional tail):
  ε ~ NSF( · | C_t )           — Conditional Spline (autoregressive with context)
  C_t = z-score normalized 7-dim macro vector at origin row
       [tbill_wr, m2_13w_cum_lag, ads_lag, cpi_13w_cum_lag, sp_std_13w,
        wti_wr, sp_log_std_13w]   (v14 cond 전체 매칭)
  base : Skew-t (Azzalini-Capitanio 2003), α learnable, df=5 (fixed)

ε 정의 (불변, unconditional train_flow_b_global.py 와 동일):
  ε = (r - r̄_train) / σ_train         (global, 단일 scalar 정규화)

Cond 정규화 (train 통계, fold-isolated):
  C_t_norm = (c_t - cond_mean_train) / cond_std_train     (per-feature z-score)

Why Conditional NSF + Skew-t base:
  • Skew-t base 는 marginal 기준 empirical skew −0.85 / kurt +6.75 capture (inductive bias)
  • Conditional spline 은 macro regime 에 따라 ε bulk/tail 모양을 시점별 조정
    (ex: 인플레/긴축기 → 왼쪽 꼬리 더 두꺼움)
  → "ε ~ Skew-t  base × per-regime spline correction" 의 의미

Architecture:
  nflows MaskedPiecewiseRationalQuadraticAutoregressiveTransform
    features=1, context_features=7,
    hidden_features=64, num_blocks=2, num_bins=16, tails="linear", tail_bound=10.0
  (features=1 이면 autoregressive masking 은 trivial — 사실상 pure conditional spline)
  num_layers = 6 (paper main)

Ckpt 형식 (호환성 + 자동 architecture 재구성):
  {
    "model_state": flow.state_dict(),
    "meta": {
        "base_kind": "skew_t",
        "df": 5.0,
        "alpha_init": -5.0, "alpha_final": <learned>,
        "num_layers": 6, "num_bins": 16, "tail_bound": 10.0, "hidden_features": 64,
        "cond_features": [...],
        "cond_mean":     [...],   # per-feature train mean
        "cond_std":      [...],   # per-feature train std (ddof=1)
        "r_mean_train":  ...,     # for sp_return reconstruction at sample time
        "r_std_train":   ...,
        "n_train":       ...,
    }
  }

Usage (per fold, fold-isolated train):
  python colab/dual_3ch/train_flow_cond.py \
      --train-csv data/folds_v33_vix_expanding/F1_train.csv \
      --save-name scenario_3m_flow_1d_cond_F1_skewt_df5.pt

Citation:
  Azzalini & Capitanio (2003). Distributions generated by perturbation of symmetry
    with emphasis on a multivariate skew t-distribution. JRSS-B 65(2), 367-389.
  Durkan, Bekasov, Murray, Papamakarios (2019). Neural Spline Flows. NeurIPS.
"""
import torch  # MUST be first

import argparse
import json
import math
import os
import sys
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")
try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

try:
    from nflows.flows.base import Flow
    from nflows.transforms import (
        CompositeTransform,
        MaskedPiecewiseRationalQuadraticAutoregressiveTransform,
    )
except ImportError:
    print("FATAL: nflows required.  pip install nflows")
    sys.exit(1)

# Skew-t base 재사용 (train_flow_b_global.py 의 SkewTBase, _StudentTLogCDF 등)
from train_flow_b_global import SkewTBase, StudentTBase   # noqa: E402

# =====================================================================
# Cond feature definition (v14 cond 전체 매칭)
# =====================================================================

COND_FEATURES_MACRO = [
    "tbill_wr",
    "m2_13w_cum_lag",
    "ads_lag",
    "cpi_13w_cum_lag",
    "sp_std_13w",
    "wti_wr",
    "sp_log_std_13w",
]
# Backward compat alias for prior 7-only callers (sensitivity reads ckpt meta for actual list)
COND_FEATURES = COND_FEATURES_MACRO


# =====================================================================
# Build conditional flow
# =====================================================================

def build_cond_flow(base_kind, df, num_layers, num_bins, tail_bound,
                    hidden_features, num_blocks, context_features,
                    alpha_init=-5.0):
    """Build 1D Conditional NSF with macro context.

    base_kind ∈ {"skew_t", "student_t"} (normal 은 baseline 으로만 가치 있어 생략).
    """
    if base_kind == "skew_t":
        base = SkewTBase(shape=[1], alpha_init=alpha_init, df=df)
    elif base_kind == "student_t":
        base = StudentTBase(shape=[1], df=df)
    else:
        raise ValueError(f"unknown base_kind={base_kind}")

    transforms = []
    for _ in range(num_layers):
        transforms.append(MaskedPiecewiseRationalQuadraticAutoregressiveTransform(
            features=1,
            hidden_features=hidden_features,
            context_features=context_features,
            num_blocks=num_blocks,
            num_bins=num_bins,
            tails="linear",
            tail_bound=tail_bound,
        ))
    return Flow(CompositeTransform(transforms), base)


# =====================================================================
# Extract (ε, C) from train CSV — fold-isolated
# =====================================================================

def _load_oof_csv(path, new_col_name):
    """Load OOF CSV (date, pred_log_std_oof) and rename pred column.

    Returns dataframe with columns ['date', new_col_name].
    """
    df = pd.read_csv(path, parse_dates=["date"])
    if "pred_log_std_oof" not in df.columns:
        raise KeyError(f"OOF CSV {path} missing column 'pred_log_std_oof'")
    out = df[["date", "pred_log_std_oof"]].rename(columns={"pred_log_std_oof": new_col_name})
    return out


def extract_eps_and_cond(train_csv, cond_features=COND_FEATURES_MACRO,
                         oof_specs=None):
    """Build (ε, C) training pairs.

    oof_specs : list of (col_name, csv_path) — appended to cond_features after macro.
                ε / r 는 row 단위, OOF prediction 은 origin date 단위 (= csv row index
                t+PAST_LEN-1). 대부분 row 가 origin 이므로 left-join 후 dropna 로 손실 최소.

    Returns (eps_t, cond_t, meta) where cond_features includes appended OOF columns.
    """
    df = pd.read_csv(train_csv, parse_dates=["date"])
    # If OOF specs provided, left-join by date and extend cond_features
    full_cond_features = list(cond_features)
    if oof_specs:
        for col, path in oof_specs:
            oof_df = _load_oof_csv(path, col)
            df = df.merge(oof_df, on="date", how="left")
            full_cond_features.append(col)
            print(f"  joined OOF: {col} ← {path}  "
                  f"(non-NaN: {df[col].notna().sum()}/{len(df)})")

    missing = [c for c in ["sp_return"] + full_cond_features if c not in df.columns]
    if missing:
        raise KeyError(f"train CSV missing columns after OOF join: {missing}")

    sub = df[["sp_return"] + full_cond_features].dropna().reset_index(drop=True)
    n = len(sub)
    cond_features = full_cond_features  # update for downstream
    if n < 30:
        raise RuntimeError(f"too few non-NaN train rows: {n}")

    r = sub["sp_return"].values.astype(np.float64)
    cond_raw = sub[cond_features].values.astype(np.float64)   # (N, K)

    # r → ε (global standardization)
    r_mean = float(r.mean())
    r_std  = float(r.std(ddof=1))
    if r_std < 1e-12:
        raise RuntimeError(f"degenerate r_std={r_std}")
    eps = ((r - r_mean) / r_std).astype(np.float32)

    # C → z-score (per feature)
    cond_mean = cond_raw.mean(axis=0)                        # (K,)
    cond_std  = cond_raw.std(axis=0, ddof=1)                 # (K,)
    cond_std_safe = np.where(cond_std < 1e-12, 1.0, cond_std)
    cond = ((cond_raw - cond_mean) / cond_std_safe).astype(np.float32)   # (N, K)

    def moments(x):
        x = np.asarray(x, dtype=np.float64)
        m, s = float(x.mean()), float(x.std(ddof=1))
        if s < 1e-12:
            return m, s, float("nan"), float("nan")
        sk = float(((x - m) ** 3).mean() / (s ** 3))
        kt = float(((x - m) ** 4).mean() / (s ** 4) - 3.0)
        return m, s, sk, kt

    rm, rs, rsk, rkt = moments(r)
    em, es, esk, ekt = moments(eps)
    print(f"  sp_return:  n={n}, mean={rm:+.6f}, std={rs:.6f}, "
          f"skew={rsk:+.3f}, ex_kurt={rkt:+.3f}, min/max=[{r.min():+.4f},{r.max():+.4f}]")
    print(f"  ε (global): mean={em:+.4f}, std={es:.4f}, "
          f"skew={esk:+.3f}, ex_kurt={ekt:+.3f}, min/max=[{eps.min():+.3f},{eps.max():+.3f}]")
    print(f"\n  Cond features (z-scored):")
    for k, f in enumerate(cond_features):
        cm = float(cond[:, k].mean())
        cs = float(cond[:, k].std(ddof=1))
        rng_lo = float(cond[:, k].min())
        rng_hi = float(cond[:, k].max())
        raw_m = float(cond_mean[k])
        raw_s = float(cond_std[k])
        print(f"    {f:20s}  raw μ={raw_m:+10.4f} σ={raw_s:.5f}  "
              f"→ z mean={cm:+.4f} std={cs:.4f} range=[{rng_lo:+.2f},{rng_hi:+.2f}]")

    eps_t  = torch.from_numpy(eps)                  # (N,)
    cond_t = torch.from_numpy(cond)                 # (N, K)
    meta = dict(
        n=n, r_mean=rm, r_std=rs,
        raw_skew=rsk, raw_ex_kurt=rkt,
        eps_skew=esk, eps_ex_kurt=ekt,
        eps_min=float(eps.min()), eps_max=float(eps.max()),
        cond_features=list(cond_features),
        cond_mean=cond_mean.tolist(),
        cond_std=cond_std.tolist(),
    )
    return eps_t, cond_t, meta


# =====================================================================
# Train loop (conditional NLL)
# =====================================================================

def train_cond_flow(eps, cond, save_path, base_kind, df, alpha_init,
                    num_layers, num_bins, tail_bound, hidden_features, num_blocks,
                    epochs, batch, lr, device, log_every=20):
    """Train conditional flow. Save with metadata. Auto-load if save_path exists."""
    K = cond.shape[1]
    if os.path.exists(save_path):
        print(f"  [SKIP] flow ckpt 이미 존재: {save_path}")
        state = torch.load(save_path, map_location=device, weights_only=False)
        meta = state["meta"]
        # K = source-of-truth = len(cond_features). context_features 키는 잘못 저장될 수 있음.
        K_meta = len(meta.get("cond_features", [])) or meta.get("context_features", K)
        flow = build_cond_flow(
            base_kind=meta.get("base_kind", base_kind),
            df=meta.get("df", df),
            num_layers=meta.get("num_layers", num_layers),
            num_bins=meta.get("num_bins", num_bins),
            tail_bound=meta.get("tail_bound", tail_bound),
            hidden_features=meta.get("hidden_features", hidden_features),
            num_blocks=meta.get("num_blocks", num_blocks),
            context_features=K_meta,
            alpha_init=meta.get("alpha_init", alpha_init),
        ).to(device)
        flow.load_state_dict(state["model_state"])
        print(f"    [load] base={meta.get('base_kind','?')}, layers={meta.get('num_layers','?')}, "
              f"bins={meta.get('num_bins','?')}, hidden={meta.get('hidden_features','?')}, "
              f"context_features={meta.get('context_features','?')}")
        # SKIP path: 호출측이 (flow, train_stats) tuple unpack 하므로 동일 형식 반환
        return flow, dict(
            n_params=sum(p.numel() for p in flow.parameters()),
            final_train_nll=meta.get("final_train_nll"),
            best_train_nll=meta.get("best_train_nll"),
            alpha_final=meta.get("alpha_final"),
            alpha_history=meta.get("alpha_history"),
            skipped=True,
        )

    flow = build_cond_flow(
        base_kind=base_kind, df=df, alpha_init=alpha_init,
        num_layers=num_layers, num_bins=num_bins, tail_bound=tail_bound,
        hidden_features=hidden_features, num_blocks=num_blocks,
        context_features=K,
    ).to(device)
    n_params = sum(p.numel() for p in flow.parameters())

    if base_kind == "skew_t":
        base_desc = f"skew_t(α_init={alpha_init:+.2f}, df={df})"
    else:
        base_desc = f"student_t(df={df})"
    print(f"  Cond NSF: base={base_desc}, layers={num_layers}, bins={num_bins}, "
          f"hidden={hidden_features}, blocks={num_blocks}, K_cond={K}, "
          f"tail={tail_bound}, params={n_params:,}")

    opt = torch.optim.Adam(flow.parameters(), lr=lr)
    eps_t  = eps.unsqueeze(-1).to(device)   # (N, 1)
    cond_t = cond.to(device)                # (N, K)
    N = eps_t.shape[0]
    print(f"  N (ε,C) = {N:,},  batch={batch},  epochs={epochs},  lr={lr}")

    best_nll = float("inf")
    alpha_history = [] if base_kind == "skew_t" else None
    for ep in range(1, epochs + 1):
        flow.train()
        perm = torch.randperm(N)
        losses = []
        for i in range(0, N, batch):
            idx = perm[i : i + batch]
            xb = eps_t[idx]
            cb = cond_t[idx]
            loss = -flow.log_prob(inputs=xb, context=cb).mean()
            opt.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(flow.parameters(), max_norm=5.0)
            opt.step()
            losses.append(loss.item())
        ep_loss = float(np.mean(losses))
        if ep_loss < best_nll:
            best_nll = ep_loss
        if alpha_history is not None:
            alpha_history.append(float(flow._distribution.alpha.detach().item()))
        if ep == 1 or ep % log_every == 0 or ep == epochs:
            a_str = ""
            if base_kind == "skew_t":
                a_str = f"  α={flow._distribution.alpha.detach().item():+.3f}"
            print(f"    flow ep{ep:>3d}: nll = {ep_loss:+.4f}   "
                  f"(best so far {best_nll:+.4f}){a_str}")

    alpha_final = None
    if base_kind == "skew_t":
        alpha_final = float(flow._distribution.alpha.detach().item())

    return flow, dict(
        n_params=n_params,
        final_train_nll=ep_loss,
        best_train_nll=best_nll,
        alpha_final=alpha_final,
        alpha_history=alpha_history,
    )


# =====================================================================
# Sanity check — sampled ε moments at C = 0 (train mean condition)
# =====================================================================

def sanity_at_mean_cond(flow, train_meta, device, n_sample=5000, seed=42):
    """Sample ε with context = 0 vector (= train mean cond after z-score).

    Compares to train ε empirical moments. At mean condition, the flow's marginal
    distribution should approximately match the unconditional train ε distribution.
    """
    flow.eval()
    torch.manual_seed(seed)
    K = len(train_meta["cond_features"])
    ctx = torch.zeros(1, K, device=device)   # 1 context → flow.sample broadcasts
    with torch.no_grad():
        # flow.sample(n, context) with context shape (B, K) returns (B, n, *event)
        eps_gen = flow.sample(n_sample, context=ctx).cpu().numpy().reshape(-1)

    def moments(x):
        m, s = float(np.mean(x)), float(np.std(x, ddof=1))
        if s < 1e-12:
            return m, s, float("nan"), float("nan")
        sk = float(np.mean((x - m) ** 3) / (s ** 3))
        kt = float(np.mean((x - m) ** 4) / (s ** 4) - 3.0)
        return m, s, sk, kt

    m, s, sk, kt = moments(eps_gen)
    print(f"\n  Sanity — sampled ε at mean cond (n={n_sample}):")
    print(f"    {'source':24s}  {'mean':>10s}  {'std':>8s}  {'skew':>8s}  {'ex_kurt':>10s}")
    print(f"    {'train ε empirical':24s}  "
          f"{0.0:+10.4f}  {1.0:>8.4f}  {train_meta['eps_skew']:+8.3f}  {train_meta['eps_ex_kurt']:+10.3f}")
    print(f"    {'Flow @ mean cond':24s}  {m:+10.4f}  {s:>8.4f}  {sk:+8.3f}  {kt:+10.3f}")

    se_skew = math.sqrt(6.0 / n_sample)
    se_kurt = math.sqrt(24.0 / n_sample)
    print(f"    SE(skew)≈{se_skew:.3f},  SE(ex_kurt)≈{se_kurt:.3f}")

    d_sk = sk - train_meta['eps_skew']
    d_kt = kt - train_meta['eps_ex_kurt']
    return dict(
        gen_mean=m, gen_std=s, gen_skew=sk, gen_ex_kurt=kt,
        delta_skew=d_sk, delta_ex_kurt=d_kt,
        se_skew=se_skew, se_kurt=se_kurt,
    )


# =====================================================================
# Main
# =====================================================================

def main():
    ap = argparse.ArgumentParser(
        description="Conditional 1D NSF: ε | macro C (Skew-t base, regime-conditional tail)")
    ap.add_argument("--train-csv", required=True,
                    help="fold train.csv (e.g. data/folds_v33_vix_expanding/F1_train.csv)")
    ap.add_argument("--result-dir", default=os.path.join(HERE, "result"))
    ap.add_argument("--save-name", required=True,
                    help="ckpt filename, e.g. scenario_3m_flow_1d_cond_F1_skewt_df5.pt")
    ap.add_argument("--har-oof-csv", default=None,
                    help="HAR-RV OOF CSV (e.g. result/har_rv_F1_train_oof.csv). "
                         "If given, appends har_oof_log_std as 8th cond feature.")
    ap.add_argument("--v14-oof-csv", default=None,
                    help="v14 MTL OOF CSV (e.g. result/v14_F1_train_oof.csv). "
                         "If given, appends v14_oof_log_std as 9th cond feature.")
    ap.add_argument("--base", choices=["skew_t", "student_t"], default="skew_t")
    ap.add_argument("--df",          type=float, default=5.0)
    ap.add_argument("--alpha-init",  type=float, default=-5.0)
    ap.add_argument("--num-layers",  type=int,   default=6)
    ap.add_argument("--num-bins",    type=int,   default=16)
    ap.add_argument("--tail-bound",  type=float, default=10.0)
    ap.add_argument("--hidden-features", type=int, default=64)
    ap.add_argument("--num-blocks",  type=int,   default=2,
                    help="MADE residual blocks per autoregressive transform")
    ap.add_argument("--epochs",      type=int,   default=200)
    ap.add_argument("--batch",       type=int,   default=256)
    ap.add_argument("--lr",          type=float, default=5e-4)
    ap.add_argument("--seed",        type=int,   default=2026)
    args = ap.parse_args()

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    repo_root = os.path.normpath(os.path.join(HERE, "..", ".."))
    train_csv = args.train_csv
    if not os.path.isabs(train_csv):
        train_csv = os.path.join(repo_root, train_csv)
    if not os.path.exists(train_csv):
        sys.exit(f"[FATAL] missing train CSV: {train_csv}")
    os.makedirs(args.result_dir, exist_ok=True)
    save_path = os.path.join(args.result_dir, args.save_name)

    print("=" * 78)
    print(" Train CONDITIONAL 1D NSF — ε | macro C")
    print("=" * 78)
    print(f"  device       : {device}")
    print(f"  train_csv    : {train_csv}")
    print(f"  save_path    : {save_path}")
    print(f"  ε def        : ε = (r - r̄_train) / σ_train    (global scalar)")
    # Compose OOF specs (optional 8th / 9th cond)
    oof_specs = []
    if args.har_oof_csv:
        oof_specs.append(("har_oof_log_std", args.har_oof_csv))
    if args.v14_oof_csv:
        oof_specs.append(("v14_oof_log_std", args.v14_oof_csv))

    print(f"  C def        : {7 + len(oof_specs)}-dim cond at origin row, z-scored on train")
    print(f"  cond macro   : {COND_FEATURES_MACRO}")
    if oof_specs:
        print(f"  cond OOF     : {[n for n, _ in oof_specs]}  (joined by date)")
    print(f"  base         : {args.base}(α_init={args.alpha_init}, df={args.df})")
    print(f"  arch         : layers={args.num_layers}, bins={args.num_bins}, "
          f"hidden={args.hidden_features}, blocks={args.num_blocks}, tail={args.tail_bound}")

    # [1] Extract (ε, C)
    print("\n[1] Extract (ε, C) — fold-isolated, train-only normalization")
    eps, cond, train_meta = extract_eps_and_cond(
        train_csv, cond_features=COND_FEATURES_MACRO, oof_specs=oof_specs,
    )

    # [2] Train
    print("\n[2] Train conditional 1D NSF")
    flow, train_stats = train_cond_flow(
        eps, cond, save_path,
        base_kind=args.base, df=args.df, alpha_init=args.alpha_init,
        num_layers=args.num_layers, num_bins=args.num_bins, tail_bound=args.tail_bound,
        hidden_features=args.hidden_features, num_blocks=args.num_blocks,
        epochs=args.epochs, batch=args.batch, lr=args.lr, device=device,
    )

    # [3] Save ckpt with meta
    meta = dict(
        base_kind=args.base, df=float(args.df),
        alpha_init=args.alpha_init, alpha_final=train_stats.get("alpha_final"),
        alpha_history=train_stats.get("alpha_history"),
        num_layers=args.num_layers, num_bins=args.num_bins, tail_bound=args.tail_bound,
        hidden_features=args.hidden_features, num_blocks=args.num_blocks,
        context_features=len(train_meta["cond_features"]),
        cond_features=train_meta["cond_features"],
        cond_mean=train_meta["cond_mean"],
        cond_std=train_meta["cond_std"],
        r_mean_train=train_meta["r_mean"],
        r_std_train=train_meta["r_std"],
        n_train=train_meta["n"],
        train_eps_skew=train_meta["eps_skew"],
        train_eps_ex_kurt=train_meta["eps_ex_kurt"],
        eps_min=train_meta["eps_min"],
        eps_max=train_meta["eps_max"],
        final_train_nll=train_stats.get("final_train_nll"),
        best_train_nll=train_stats.get("best_train_nll"),
        n_params=train_stats.get("n_params"),
        seed=args.seed,
        train_csv=os.path.abspath(train_csv),
    )
    torch.save({"model_state": flow.state_dict(), "meta": meta}, save_path)
    print(f"\n  saved ckpt: {save_path}  (n_params={meta['n_params']:,}, "
          f"final NLL={meta['final_train_nll']:+.4f})")

    # [4] Sanity (sample at mean condition)
    print("\n[3] Sanity — sample at C = 0 (mean cond)")
    sanity = sanity_at_mean_cond(flow, train_meta, device, n_sample=5000)

    # [5] Meta JSON (human-readable)
    meta_json_path = save_path.replace(".pt", "_meta.json")
    meta_for_json = {k: v for k, v in meta.items() if k != "alpha_history"}
    meta_for_json["sanity_at_mean_cond"] = sanity
    with open(meta_json_path, "w") as f:
        json.dump(meta_for_json, f, indent=2, default=str)
    print(f"\n  meta saved: {meta_json_path}")

    print("\n" + "=" * 78)
    print(" SUMMARY")
    print("=" * 78)
    print(f"  Base                : {args.base}(α_init={args.alpha_init:+.2f}, df={args.df})")
    if train_stats.get("alpha_final") is not None:
        print(f"  Learned α           : {args.alpha_init:+.3f} → {train_stats['alpha_final']:+.3f}")
    print(f"  Train ε emp         : skew={train_meta['eps_skew']:+.3f}, "
          f"ex_kurt={train_meta['eps_ex_kurt']:+.3f}")
    print(f"  Flow @ mean cond    : skew={sanity['gen_skew']:+.3f}, "
          f"ex_kurt={sanity['gen_ex_kurt']:+.3f}")
    print(f"    → Δskew = {sanity['delta_skew']:+.3f}, "
          f"Δex_kurt = {sanity['delta_ex_kurt']:+.3f}")
    print(f"  cond_mean (raw)     : {[round(x,4) for x in meta['cond_mean']]}")
    print(f"  cond_std  (raw)     : {[round(x,4) for x in meta['cond_std']]}")
    print(f"  r_mean_train        : {meta['r_mean_train']:+.6f}")
    print(f"  r_std_train         : {meta['r_std_train']:.6f}")


if __name__ == "__main__":
    main()
